### ISSUE TITLE
Unable to decompress Jetraw images in  Fidji

### ISSUE THREAD

**Issue by clementhelsens** [Jetraw/bioformats_jetraw#10]
Hello, 

we've (with @feyzanar) been having some issues lately with decompressing JetRaw compressed images using the Fidji plugin.
Using a fresh Fidji and following the instructions for windows we see the type of error below.
We are running windows server 2022 and that might be the problem, but I have too little experience with windows OS to be sure.
Any help would be welcome, thanks!

```
(Fiji Is Just) ImageJ 2.3.0/1.54f; Java 1.8.0_172 [64-bit]; Windows Server 2016 10.0; 163MB of 785135MB (<1%)
java.lang.UnsatisfiedLinkError: C:\Users\venzin\AppData\Local\Temp\3\jetraw_bioformats_plugin.dll1298498267524113079: The specified procedure could not be found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at loci.formats.codec.DotphotonCodec.loadLib(DotphotonCodec.java:77)
	at loci.formats.codec.DotphotonCodec.decompress(DotphotonCodec.java:113)
	at loci.formats.tiff.TiffCompression.decompress(TiffCompression.java:284)
	at loci.formats.tiff.TiffParser.getTile(TiffParser.java:831)
	at loci.formats.tiff.TiffParser.getSamples(TiffParser.java:1109)
	at loci.formats.tiff.TiffParser.getSamples(TiffParser.java:871)
	at [loci.formats.in](http://loci.formats.in/).OMETiffReader.openBytes(OMETiffReader.java:351)
	at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:167)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:229)
	at loci.formats.ChannelSeparator.openBytes(ChannelSeparator.java:161)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.formats.DimensionSwapper.openBytes(DimensionSwapper.java:233)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
	at loci.plugins.util.ImageProcessorReader.openProcessors(ImageProcessorReader.java:186)
	at loci.plugins.util.ImageProcessorReader.openProcessors(ImageProcessorReader.java:83)
	at loci.plugins.util.ImageProcessorSource.getObject(ImageProcessorSource.java:72)
	at loci.formats.cache.Cache.recache(Cache.java:204)
	at loci.formats.cache.Cache.recache(Cache.java:224)
	at loci.formats.cache.Cache.<init>(Cache.java:88)
	at loci.plugins.util.BFVirtualStack.<init>(BFVirtualStack.java:126)
	at [loci.plugins.in](http://loci.plugins.in/).ImagePlusReader.createVirtualStack(ImagePlusReader.java:339)
	at [loci.plugins.in](http://loci.plugins.in/).ImagePlusReader.readImage(ImagePlusReader.java:281)
	at [loci.plugins.in](http://loci.plugins.in/).ImagePlusReader.readImages(ImagePlusReader.java:243)
	at [loci.plugins.in](http://loci.plugins.in/).ImagePlusReader.readImages(ImagePlusReader.java:221)
	at [loci.plugins.in](http://loci.plugins.in/).ImagePlusReader.openImagePlus(ImagePlusReader.java:116)
	at [loci.plugins.in](http://loci.plugins.in/).Importer.readPixels(Importer.java:149)
	at [loci.plugins.in](http://loci.plugins.in/).Importer.run(Importer.java:86)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.IJ.runPlugIn(IJ.java:199)
	at HandleExtraFileTypes.openImage(HandleExtraFileTypes.java:503)
	at HandleExtraFileTypes.run(HandleExtraFileTypes.java:76)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.IJ.runPlugIn(IJ.java:199)
	at [ij.io](http://ij.io/).Opener.openWithHandleExtraFileTypes(Opener.java:556)
	at [ij.io](http://ij.io/).Opener.openUsingHandleExtraFileTypes(Opener.java:407)
	at [ij.io](http://ij.io/).Opener.openImage(Opener.java:386)
	at [ij.io](http://ij.io/).Opener.openImage(Opener.java:241)
	at [ij.io](http://ij.io/).Opener.open(Opener.java:104)
	at [ij.io](http://ij.io/).Opener.openAndAddToRecent(Opener.java:310)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:194)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:160)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by clementhelsens** [comment]
**UPDATE**: after spending some time with @NicoKiaru, it seems that this simple `System.load` is the source of the problem, see screenshot.

<img width="1361" alt="Screenshot 2024-01-09 at 13 01 35" src="https://github.com/Jetraw/bioformats_jetraw/assets/5268237/3af5af2d-ef4e-4cac-8a51-443ebd5924e8">

**Comment by NicoKiaru** [comment]
Loading the dll also fails on my machine. 

I've listed the dependents [thanks to this post](https://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency). Here's the output:


```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64>dumpbin /dependents E:\Fiji_20201029-1752\jetraw_bioformats_plugin.dll
Microsoft (R) COFF/PE Dumper Version 14.35.32215.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file E:\Fiji_20201029-1752\jetraw_bioformats_plugin.dll

File Type: DLL

  Image has the following dependencies:

    jetraw.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll

  Summary

        1000 .00cfg
        1000 .data
        1000 .gehcont
        1000 .pdata
        2000 .rdata
        1000 .reloc
        1000 .rsrc
        2000 .text
        1000 .voltbl

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64>
```

**Comment by NicoKiaru** [comment]
`jetraw.dll` is listed. Is Jetraw (a standalone application?) installed @clementhelsens ?

**Comment by clementhelsens** [comment]
yes, it's taken from here:
https://www.jetraw.com/downloads/software

**Comment by NicoKiaru** [comment]
Ah! With this installed (on my side), I get a different error:

```
Started Untitled.groovy at Tue Jan 09 14:13:11 CET 2024
java.lang.UnsatisfiedLinkError: E:\Fiji_20201029-1752\jetraw_bioformats_plugin.dll: The specified procedure could not be found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
```

So, a different error message. As far as I'm concerned, it's not a big issue. 

```
System.load("E:/Fiji_20201029-1752/jetraw_bioformats_plugin.dll");
```

**Comment by arvequina** [comment]
Hello @clementhelsens and @NicoKiaru 

Thank you for your inquiry and for using Jetraw. 

The issue you are currently facing, it is a known bug that we are working on. There is a mismatch between the jetraw library and the fiji plug-in, introduced in the latest jetraw release (23.03.16.4). If you go back to the previous jetraw version [(22.02.16.1)](https://github.com/Jetraw/Jetraw/releases/download/22.02.16.1/JetrawWithDPCore-22.02.16.1.msi) everything should work fine again. 

We will probably release a fix during this month and sorry for the inconvenience.

**Comment by clementhelsens** [comment]
thanks @arvequina , but we are already running 22.02.16.1 see screenshot
<img width="1089" alt="Screenshot 2024-01-09 at 14 33 39" src="https://github.com/Jetraw/bioformats_jetraw/assets/5268237/e424dffe-4b5d-4848-92f7-ea24d673c8c8">

**Comment by NicoKiaru** [comment]
So, problem fixed. Turns out, the `jetraw.dll` file was in `C:/Program Files/Jetraw/bin64` but this path was not present in the Path system environment variable. Thus loading the dll `jetraw_bioformats_plugin.dll` in Fiji failed because it couldn't find `jetraw.dll`.

We added `C:/Program Files/Jetraw/bin64` in the Path system env variable and this fixed the issue.

Shouldn't installing Jetraw automatically add its dll path to the Path env var ? Because it seems that this was the cause of this issue.

**Comment by arvequina** [comment]
@clementhelsens I thought that you had downloaded the latest version from the website, sorry! 

@NicoKiaru yes, it should be added automatically to `PATH`, perhaps you need admin privileges to do so in that computer? The windows installer adds the jetraw `bin` folder to the path so the dependencies can be found properly.

**Comment by clementhelsens** [comment]
@arvequina , what is weird is that the lab uses jetraw since few years already, and suddenly few weeks ago this problem appeared. It took us some time to sort it out. Do you think you could discuss this issue with your boss asking if we could get a licence extension for the duration we couldn't use it to decompress our files?

**Comment by arvequina** [comment]
@clementhelsens our sales rep will contact you privately. Have a good one and thanks for your comments.
